name: Tests and unit coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-coverage:
    name: unit-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.23"
      - name: Install project Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --locked --all-groups
      - name: Run integration tests
        run: uv run pytest tests/integration
      - name: Measure unit test coverage
        run: >-
          uv run pytest tests/unit
          --cov=localinteractiveairesponder
          --cov-report=term-missing
          --cov-fail-under=80
